#include "cHacks.h"
#include "params.h"
#include "hostable.h"

extern const u8 hosTables[6][0xff][0xff] = {
	HOS_TABLE(CAMERA_MIN_HEIGHT),
	HOS_TABLE((CAMERA_MIN_HEIGHT+CAMERA_Z_STEP)),
	HOS_TABLE((CAMERA_MIN_HEIGHT+(2*CAMERA_Z_STEP))),
	HOS_TABLE((CAMERA_MIN_HEIGHT+(3*CAMERA_Z_STEP))),
	HOS_TABLE((CAMERA_MIN_HEIGHT+(4*CAMERA_Z_STEP))),
	HOS_TABLE((CAMERA_MIN_HEIGHT+(5*CAMERA_Z_STEP)))
};